version: "3"
services:
  data-lake:
    network_mode: host
    build:
      context: .
      dockerfile: data-lake/Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./knowledge-graph/neo4j/:/home/knowledge-graph/neo4j
      - ./index/:/index
  entity-linker:
    network_mode: host
    build:
      context: .
      dockerfile: entity-linker/Dockerfile
    ports:
      - 8082:8082
    volumes:
      - ./knowledge-graph/neo4j/:/home/knowledge-graph/neo4j
      - ./index/:/index
  ekg-manager:
    network_mode: host
    build:
      context: .
      dockerfile: knowledge-graph/Dockerfile
    ports:
      - 8083:8083
    volumes:
      - ./knowledge-graph/neo4j/:/home/knowledge-graph/neo4j
      - ./index/:/index
  embeddings:
    image: postgres
    container_name: db
    network_mode: host
    environment:
      - POSTGRES_USER=calypso
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=embeddings