version: "3"
services:
  data-lake:
    network_mode: host
    build:
      context: .
      dockerfile: data-lake/Dockerfile
    ports:
      - 8081:8081
  entity-linker:
    network_mode: host
    build:
      context: .
      dockerfile: entity-linker/Dockerfile
    ports:
      - 8082:8082
  ekg-manager:
    network_mode: host
    build:
      context: .
      dockerfile: knowledge-graph/Dockerfile
    ports:
      - 8083:8083
    volumes:
      - ./knowledge-graph/neo4j/:/home/knowledge-graph/neo4j
