version: "3"

services:
  web:
    container_name: jazero_web
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile

  proxy:
    image: nginx:1.15-alpine
    network_mode: host
    container_name: nginx_proxy
    restart: unless-stopped
    depends_on: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    links:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"